baseURL = 'https://next.unblock.health/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke" 
[markup]
defaultMarkdownHandler            = "goldmark"

[markup.goldmark.renderer]
unsafe                            = true
[params]
topNavbarMenu                     = ["Home","About","Services","Register","News","Press","Events","Blog","FAQs","Patient Impact Stories"]
topNavbarMenuLink                 = ["/","#about","#service","/register","/news","/press","/events","/blog","/faqs","/patient-impact-stories"]
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML","Calendar"]
events = ["HTML","Calendar"]
section = ["HTML","RSS","JSON"]
[outputFormats.Calendar]
protocol = "http://" 
[date]
date = ["enddate", ":default"]
