[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  [[redirects]]
  from = "/events/images/default.png"
  to = "/events/"
  status = 301
  force = true

  [[redirects]]
  from = "/events/patient-access-of-phi-and-communications/images/default.png"
  to = "/events/"
  status = 301
  force = true

